version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3
  aws-ecs: circleci/aws-ecs@2.2.1
  aws-ecr: circleci/aws-ecr@6.15.0
  
jobs:
  run_tests:
    docker:
      - image: circleci/node:17.1
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run unit tests
          command: |
            npm test
      - store_test_results:
          path: test-results
      
workflows:
  build_test_deploy:
    jobs:
      - run_tests
      #Envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION, AWS_ECR_ACCOUNT_URL
      - aws-ecr/build-and-push-image:
          requires:
            - run_tests
          filters:
            branches:
              only:
                - master    
          dockerfile: Dockerfile
          path: .  
          repo: '${MY_APP_PREFIX}'
          tag: "$CIRCLE_SHA1"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: '${MY_APP_PREFIX}-service'
          cluster-name: '${MY_APP_PREFIX}-cluster'
          container-image-name-updates: 'container=${MY_APP_PREFIX}-service,image-and-tag=884479076076.dkr.ecr.us-east-2.amazonaws.com/boc-backend:"$CIRCLE_SHA1"'
          
          #884479076076.dkr.ecr.us-east-2.amazonaws.com/bocserver:latest