version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3
  aws-ecs: circleci/aws-ecs@2.0
  
jobs:
  run_tests:
    docker:
      - image: circleci/node:17.1
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run unit tests
          command: |
            npm test
      - store_test_results:
          path: test-results
  update-tag:
      docker:
        - image: 'circleci/node:17.1'
      steps:
        - aws-cli/setup:
            aws-access-key-id: AWS_SECRET_ACCESS_KEY_ID
            aws-region: AWS_DEFAULT_REGION
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY
        - aws-ecs/update-service:
            cluster-name: '${MY_APP_PREFIX}-cluster'
            container-image-name-updates: 'container=bocserver-service,tag=latest'
            family: 'boc-server-service'
  # build_and_deploy:
  #   docker:
  #     - image: circleci/node:17.1
  #       auth:
  #         username: $DOCKERHUB_USER
  #         password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install npm dependencies
  #         command: |
  #           npm install --save
  #     - run:
  #         name: Run unit tests
  #         command: |
  #           npm test
  #     - store_test_results:
  #         path: test-results

  #     - setup_remote_docker:
  #         version: 20.10.11
  #         docker_layer_caching: true

  #     # build and push Docker image
  #     - run: |
  #         docker build -t juanacosta00/boc-api:$TAG .
  #         echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
  #         docker push juanacosta00/boc-api:$TAG
workflows:
  build_test_deploy:
    jobs:
      - run_tests
      - update-tag:
          requires:
            - run_tests
          filters:
            branches:
              only:
                - master